/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as HrResultsRouteImport } from './routes/hr-results'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as GameRouteImport } from './routes/game'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CookandcreateRouteRouteImport } from './routes/cookandcreate/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookandcreateIndexRouteImport } from './routes/cookandcreate/index'
import { Route as JoinLinkTokenRouteImport } from './routes/join.$linkToken'
import { Route as CookandcreateSummaryRouteImport } from './routes/cookandcreate/summary'
import { Route as CookandcreateRatingRouteImport } from './routes/cookandcreate/rating'
import { Route as CookandcreateLobbyRouteImport } from './routes/cookandcreate/lobby'
import { Route as CookandcreateGameRouteImport } from './routes/cookandcreate/game'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const HrResultsRoute = HrResultsRouteImport.update({
  id: '/hr-results',
  path: '/hr-results',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CookandcreateRouteRoute = CookandcreateRouteRouteImport.update({
  id: '/cookandcreate',
  path: '/cookandcreate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookandcreateIndexRoute = CookandcreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CookandcreateRouteRoute,
} as any)
const JoinLinkTokenRoute = JoinLinkTokenRouteImport.update({
  id: '/join/$linkToken',
  path: '/join/$linkToken',
  getParentRoute: () => rootRouteImport,
} as any)
const CookandcreateSummaryRoute = CookandcreateSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => CookandcreateRouteRoute,
} as any)
const CookandcreateRatingRoute = CookandcreateRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => CookandcreateRouteRoute,
} as any)
const CookandcreateLobbyRoute = CookandcreateLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => CookandcreateRouteRoute,
} as any)
const CookandcreateGameRoute = CookandcreateGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => CookandcreateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookandcreate': typeof CookandcreateRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/groups': typeof GroupsRoute
  '/hr-results': typeof HrResultsRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/participants': typeof ParticipantsRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/cookandcreate/game': typeof CookandcreateGameRoute
  '/cookandcreate/lobby': typeof CookandcreateLobbyRoute
  '/cookandcreate/rating': typeof CookandcreateRatingRoute
  '/cookandcreate/summary': typeof CookandcreateSummaryRoute
  '/join/$linkToken': typeof JoinLinkTokenRoute
  '/cookandcreate/': typeof CookandcreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/groups': typeof GroupsRoute
  '/hr-results': typeof HrResultsRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/participants': typeof ParticipantsRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/cookandcreate/game': typeof CookandcreateGameRoute
  '/cookandcreate/lobby': typeof CookandcreateLobbyRoute
  '/cookandcreate/rating': typeof CookandcreateRatingRoute
  '/cookandcreate/summary': typeof CookandcreateSummaryRoute
  '/join/$linkToken': typeof JoinLinkTokenRoute
  '/cookandcreate': typeof CookandcreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookandcreate': typeof CookandcreateRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/groups': typeof GroupsRoute
  '/hr-results': typeof HrResultsRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/participants': typeof ParticipantsRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/cookandcreate/game': typeof CookandcreateGameRoute
  '/cookandcreate/lobby': typeof CookandcreateLobbyRoute
  '/cookandcreate/rating': typeof CookandcreateRatingRoute
  '/cookandcreate/summary': typeof CookandcreateSummaryRoute
  '/join/$linkToken': typeof JoinLinkTokenRoute
  '/cookandcreate/': typeof CookandcreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookandcreate'
    | '/create'
    | '/dashboard'
    | '/game'
    | '/groups'
    | '/hr-results'
    | '/lobby'
    | '/login'
    | '/notifications'
    | '/participants'
    | '/payments'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/terms'
    | '/cookandcreate/game'
    | '/cookandcreate/lobby'
    | '/cookandcreate/rating'
    | '/cookandcreate/summary'
    | '/join/$linkToken'
    | '/cookandcreate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/dashboard'
    | '/game'
    | '/groups'
    | '/hr-results'
    | '/lobby'
    | '/login'
    | '/notifications'
    | '/participants'
    | '/payments'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/terms'
    | '/cookandcreate/game'
    | '/cookandcreate/lobby'
    | '/cookandcreate/rating'
    | '/cookandcreate/summary'
    | '/join/$linkToken'
    | '/cookandcreate'
  id:
    | '__root__'
    | '/'
    | '/cookandcreate'
    | '/create'
    | '/dashboard'
    | '/game'
    | '/groups'
    | '/hr-results'
    | '/lobby'
    | '/login'
    | '/notifications'
    | '/participants'
    | '/payments'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/terms'
    | '/cookandcreate/game'
    | '/cookandcreate/lobby'
    | '/cookandcreate/rating'
    | '/cookandcreate/summary'
    | '/join/$linkToken'
    | '/cookandcreate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookandcreateRouteRoute: typeof CookandcreateRouteRouteWithChildren
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  GameRoute: typeof GameRoute
  GroupsRoute: typeof GroupsRoute
  HrResultsRoute: typeof HrResultsRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ParticipantsRoute: typeof ParticipantsRoute
  PaymentsRoute: typeof PaymentsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  TermsRoute: typeof TermsRoute
  JoinLinkTokenRoute: typeof JoinLinkTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-results': {
      id: '/hr-results'
      path: '/hr-results'
      fullPath: '/hr-results'
      preLoaderRoute: typeof HrResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookandcreate': {
      id: '/cookandcreate'
      path: '/cookandcreate'
      fullPath: '/cookandcreate'
      preLoaderRoute: typeof CookandcreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookandcreate/': {
      id: '/cookandcreate/'
      path: '/'
      fullPath: '/cookandcreate/'
      preLoaderRoute: typeof CookandcreateIndexRouteImport
      parentRoute: typeof CookandcreateRouteRoute
    }
    '/join/$linkToken': {
      id: '/join/$linkToken'
      path: '/join/$linkToken'
      fullPath: '/join/$linkToken'
      preLoaderRoute: typeof JoinLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookandcreate/summary': {
      id: '/cookandcreate/summary'
      path: '/summary'
      fullPath: '/cookandcreate/summary'
      preLoaderRoute: typeof CookandcreateSummaryRouteImport
      parentRoute: typeof CookandcreateRouteRoute
    }
    '/cookandcreate/rating': {
      id: '/cookandcreate/rating'
      path: '/rating'
      fullPath: '/cookandcreate/rating'
      preLoaderRoute: typeof CookandcreateRatingRouteImport
      parentRoute: typeof CookandcreateRouteRoute
    }
    '/cookandcreate/lobby': {
      id: '/cookandcreate/lobby'
      path: '/lobby'
      fullPath: '/cookandcreate/lobby'
      preLoaderRoute: typeof CookandcreateLobbyRouteImport
      parentRoute: typeof CookandcreateRouteRoute
    }
    '/cookandcreate/game': {
      id: '/cookandcreate/game'
      path: '/game'
      fullPath: '/cookandcreate/game'
      preLoaderRoute: typeof CookandcreateGameRouteImport
      parentRoute: typeof CookandcreateRouteRoute
    }
  }
}

interface CookandcreateRouteRouteChildren {
  CookandcreateGameRoute: typeof CookandcreateGameRoute
  CookandcreateLobbyRoute: typeof CookandcreateLobbyRoute
  CookandcreateRatingRoute: typeof CookandcreateRatingRoute
  CookandcreateSummaryRoute: typeof CookandcreateSummaryRoute
  CookandcreateIndexRoute: typeof CookandcreateIndexRoute
}

const CookandcreateRouteRouteChildren: CookandcreateRouteRouteChildren = {
  CookandcreateGameRoute: CookandcreateGameRoute,
  CookandcreateLobbyRoute: CookandcreateLobbyRoute,
  CookandcreateRatingRoute: CookandcreateRatingRoute,
  CookandcreateSummaryRoute: CookandcreateSummaryRoute,
  CookandcreateIndexRoute: CookandcreateIndexRoute,
}

const CookandcreateRouteRouteWithChildren =
  CookandcreateRouteRoute._addFileChildren(CookandcreateRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookandcreateRouteRoute: CookandcreateRouteRouteWithChildren,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  GameRoute: GameRoute,
  GroupsRoute: GroupsRoute,
  HrResultsRoute: HrResultsRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ParticipantsRoute: ParticipantsRoute,
  PaymentsRoute: PaymentsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  TermsRoute: TermsRoute,
  JoinLinkTokenRoute: JoinLinkTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
